name: Build and Publish a tagged Application Image

on:
  push:
    tags:
      - 'ehealthid-relying-party/v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Get version
        id: version
        run: |
          echo "parsing version from ref '$GITHUB_REF'"
          VERSION=$(echo "$GITHUB_REF" | sed -e 's|.*/ehealthid-relying-party/v\(.*\)|\1|g')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - id: buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Update Version
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          echo "updating version to '$VERSION'"
          make update-version "VERSION=$VERSION"
      - name: Build and push Image
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          make dist RELEASE_TAG=v$VERSION