name: Build and Publish Application Image

on:
  push:
    tags:
      - 'ehealthid-relying-party/v[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'

jobs:
  deploy:
    env:
      DOCKER_REPO: 'europe-docker.pkg.dev/oviva-pkg/ovi/'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Get version
        id: version
        run: |
          echo "parsing version from ref '$GITHUB_REF'"
          VERSION=$(echo "$GITHUB_REF" | sed -e 's|.*/ehealthid-relying-party/v\(.*\)|\1|g')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Update Version
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          echo "updating version to '$VERSION'"
          make update-version "VERSION=$VERSION"
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/155692196363/locations/global/workloadIdentityPools/github-actions-sa/providers/github-actions-sa
          service_account: gh-wi-main-registry-writer-gh@github-actions-sa.iam.gserviceaccount.com
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: europe-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Image
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          make dist RELEASE_TAG=v$VERSION
    permissions:
      contents: read
      id-token: write