name: Spotless Linter

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      MAVEN_USERNAME: continuousintegration-oviva
      MAVEN_PASSWORD: ${{ secrets.MAVEN_REPO_TOKEN }}
    permissions:
      contents: read
      packages: read
      checks: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          cache: 'maven'
      - name: run spotless
        id: spotless
        run: ./mvnw -B spotless:check
      - name: check spotless
        if: always()
        uses: oviva-ag/checks-action@v1.2.0
        with:
          name: Check spotless output
          token: ${{ secrets.GITHUB_TOKEN }}
          conclusion: ${{ steps.spotless.outcome }}